/*
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.ide;


/**
 * Use this class to register ide components.
 */
public class MinotorDslIdeModule extends AbstractMinotorDslIdeModule {
}
