/*
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.mit.dipterv.text.MinotorDslRuntimeModule;
import hu.bme.mit.dipterv.text.MinotorDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MinotorDslIdeSetup extends MinotorDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MinotorDslRuntimeModule(), new MinotorDslIdeModule()));
	}
	
}
