language: java
install: true
jdk:
  - openjdk11

os:
  - linux

script:
 - mvn clean install -U
 - cd hu.bme.mit.dipterv.text.example
 - mvn clean install -U
 - cd ../hu.bme.mit.dipterv.text.mobileexample
 - mvn clean install -U
 - cd ../hu.bme.mit.dipterv.text.altexample
 - mvn clean install -U
 - cd ../hu.bme.mit.dipterv.text.parexample
 - mvn clean install -U
 - cd ../hu.bme.mit.dipterv.text.operatorexample
 - mvn clean install -U
