/*
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MinotorDslUiModule extends AbstractMinotorDslUiModule {

	public MinotorDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
