/*
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MinotorDslStandaloneSetup extends MinotorDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MinotorDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
