/*
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MinotorDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("hu/bme/mit/dipterv/text/parser/antlr/internal/InternalMinotorDsl.tokens");
	}
}
