/*
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class MinotorDslProposalProvider extends AbstractMinotorDslProposalProvider {
}
