/*
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.ui;

import com.google.inject.Injector;
import hu.bme.mit.dipterv.text.ui.internal.TextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MinotorDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TextActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TextActivator activator = TextActivator.getInstance();
		return activator != null ? activator.getInjector(TextActivator.HU_BME_MIT_DIPTERV_TEXT_MINOTORDSL) : null;
	}

}
