/*
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.ui.tests;

import com.google.inject.Injector;
import hu.bme.mit.dipterv.text.ui.internal.TextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MinotorDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TextActivator.getInstance().getInjector("hu.bme.mit.dipterv.text.MinotorDsl");
	}

}
