/*
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.tests


import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.eclipse.xtext.xbase.testing.CompilationTestHelper

@ExtendWith(InjectionExtension)
@InjectWith(MinotorDslInjectorProvider)
class MinotorDslParsingTest {
	@Inject extension CompilationTestHelper
 
 	/*
	@Test def testSimpleMessage() {

	     '''
	         specification spec1{

	         	object Computer computer;

	         	scenario email {
	         		message checkEmail() computer -> computer;
	         	}
	         }
	     '''.assertCompilesTo('''''')
	}*/
}
