/*
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.tests


import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(MinotorDslInjectorProvider)
class MinotorDslParsingTest {
	/*@Inject
	ParseHelper<Domain> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Inject extension CompilationTestHelper
 
	@Test def test() {
	     '''
	         datatype String

	         package my.company.blog {
	             entity Blog {
	                 title: String
	             }
	         }
	     '''.assertCompilesTo('''
	         package my.company.blog;

	         public class Blog {
	             private String title;

	             public String getTitle() {
	                 return title;
	             }
		             public void setTitle(String title) {
	                 this.title = title;
	             }
	         }
	     ''')
	}*/
}
