/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.AndExpression#getLhs <em>Lhs</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.AndExpression#getRhs <em>Rhs</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getAndExpression()
 * @model
 * @generated
 */
public interface AndExpression extends BinaryLogicalExpression
{
  /**
   * Returns the value of the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lhs</em>' containment reference.
   * @see #setLhs(LogicalExpression)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getAndExpression_Lhs()
   * @model containment="true"
   * @generated
   */
  LogicalExpression getLhs();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.AndExpression#getLhs <em>Lhs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lhs</em>' containment reference.
   * @see #getLhs()
   * @generated
   */
  void setLhs(LogicalExpression value);

  /**
   * Returns the value of the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rhs</em>' containment reference.
   * @see #setRhs(LogicalExpression)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getAndExpression_Rhs()
   * @model containment="true"
   * @generated
   */
  LogicalExpression getRhs();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.AndExpression#getRhs <em>Rhs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rhs</em>' containment reference.
   * @see #getRhs()
   * @generated
   */
  void setRhs(LogicalExpression value);

} // AndExpression
