/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assertion Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.AssertionRelation#getContext <em>Context</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.AssertionRelation#getRelation <em>Relation</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.AssertionRelation#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.AssertionRelation#getOperator <em>Operator</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.AssertionRelation#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getAssertionRelation()
 * @model
 * @generated
 */
public interface AssertionRelation extends EObject
{
  /**
   * Returns the value of the '<em><b>Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' reference.
   * @see #setContext(ContextModel)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getAssertionRelation_Context()
   * @model
   * @generated
   */
  ContextModel getContext();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.AssertionRelation#getContext <em>Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' reference.
   * @see #getContext()
   * @generated
   */
  void setContext(ContextModel value);

  /**
   * Returns the value of the '<em><b>Relation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relation</em>' reference.
   * @see #setRelation(Relation)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getAssertionRelation_Relation()
   * @model
   * @generated
   */
  Relation getRelation();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.AssertionRelation#getRelation <em>Relation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relation</em>' reference.
   * @see #getRelation()
   * @generated
   */
  void setRelation(Relation value);

  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getAssertionRelation_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.AssertionRelation#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.dipterv.text.minotorDsl.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' containment reference list.
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getAssertionRelation_Operator()
   * @model containment="true"
   * @generated
   */
  EList<Operator> getOperator();

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.dipterv.text.minotorDsl.AttributeValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference list.
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getAssertionRelation_Value()
   * @model containment="true"
   * @generated
   */
  EList<AttributeValue> getValue();

} // AssertionRelation
