/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Change To Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.ChangeToMessage#getContext <em>Context</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.ChangeToMessage#getEntity <em>Entity</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.ChangeToMessage#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.ChangeToMessage#getChangevalue <em>Changevalue</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getChangeToMessage()
 * @model
 * @generated
 */
public interface ChangeToMessage extends EObject
{
  /**
   * Returns the value of the '<em><b>Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' reference.
   * @see #setContext(ContextModel)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getChangeToMessage_Context()
   * @model
   * @generated
   */
  ContextModel getContext();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.ChangeToMessage#getContext <em>Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' reference.
   * @see #getContext()
   * @generated
   */
  void setContext(ContextModel value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference.
   * @see #setEntity(Entity)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getChangeToMessage_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.ChangeToMessage#getEntity <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getChangeToMessage_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.ChangeToMessage#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Changevalue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Changevalue</em>' containment reference.
   * @see #setChangevalue(AttributeValue)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getChangeToMessage_Changevalue()
   * @model containment="true"
   * @generated
   */
  AttributeValue getChangevalue();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.ChangeToMessage#getChangevalue <em>Changevalue</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Changevalue</em>' containment reference.
   * @see #getChangevalue()
   * @generated
   */
  void setChangevalue(AttributeValue value);

} // ChangeToMessage
