/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clock Constraint Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.ClockConstraintExpression#isNot <em>Not</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.ClockConstraintExpression#getLclockconstraint <em>Lclockconstraint</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.ClockConstraintExpression#getRclockconstraint <em>Rclockconstraint</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getClockConstraintExpression()
 * @model
 * @generated
 */
public interface ClockConstraintExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not</em>' attribute.
   * @see #setNot(boolean)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getClockConstraintExpression_Not()
   * @model
   * @generated
   */
  boolean isNot();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.ClockConstraintExpression#isNot <em>Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not</em>' attribute.
   * @see #isNot()
   * @generated
   */
  void setNot(boolean value);

  /**
   * Returns the value of the '<em><b>Lclockconstraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lclockconstraint</em>' containment reference.
   * @see #setLclockconstraint(ClockConstraint)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getClockConstraintExpression_Lclockconstraint()
   * @model containment="true"
   * @generated
   */
  ClockConstraint getLclockconstraint();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.ClockConstraintExpression#getLclockconstraint <em>Lclockconstraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lclockconstraint</em>' containment reference.
   * @see #getLclockconstraint()
   * @generated
   */
  void setLclockconstraint(ClockConstraint value);

  /**
   * Returns the value of the '<em><b>Rclockconstraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rclockconstraint</em>' containment reference.
   * @see #setRclockconstraint(ClockConstraint)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getClockConstraintExpression_Rclockconstraint()
   * @model containment="true"
   * @generated
   */
  ClockConstraint getRclockconstraint();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.ClockConstraintExpression#getRclockconstraint <em>Rclockconstraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rclockconstraint</em>' containment reference.
   * @see #getRclockconstraint()
   * @generated
   */
  void setRclockconstraint(ClockConstraint value);

} // ClockConstraintExpression
