/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Message Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.ContextMessageContent#getMatch <em>Match</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.ContextMessageContent#getChange <em>Change</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getContextMessageContent()
 * @model
 * @generated
 */
public interface ContextMessageContent extends EObject
{
  /**
   * Returns the value of the '<em><b>Match</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.dipterv.text.minotorDsl.MatchMessage}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Match</em>' containment reference list.
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getContextMessageContent_Match()
   * @model containment="true"
   * @generated
   */
  EList<MatchMessage> getMatch();

  /**
   * Returns the value of the '<em><b>Change</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.dipterv.text.minotorDsl.ChangeMessage}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Change</em>' containment reference list.
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getContextMessageContent_Change()
   * @model containment="true"
   * @generated
   */
  EList<ChangeMessage> getChange();

} // ContextMessageContent
