/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Disappear Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.DisappearMessage#getContext <em>Context</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.DisappearMessage#getEntity <em>Entity</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getDisappearMessage()
 * @model
 * @generated
 */
public interface DisappearMessage extends EObject
{
  /**
   * Returns the value of the '<em><b>Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' reference.
   * @see #setContext(ContextModel)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getDisappearMessage_Context()
   * @model
   * @generated
   */
  ContextModel getContext();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.DisappearMessage#getContext <em>Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' reference.
   * @see #getContext()
   * @generated
   */
  void setContext(ContextModel value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference.
   * @see #setEntity(Entity)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getDisappearMessage_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.DisappearMessage#getEntity <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

} // DisappearMessage
