/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equals Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.EqualsExpression#getLhs <em>Lhs</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.EqualsExpression#getRhs <em>Rhs</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getEqualsExpression()
 * @model
 * @generated
 */
public interface EqualsExpression extends BinaryLogicalExpression
{
  /**
   * Returns the value of the '<em><b>Lhs</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lhs</em>' reference.
   * @see #setLhs(Parameter)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getEqualsExpression_Lhs()
   * @model
   * @generated
   */
  Parameter getLhs();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.EqualsExpression#getLhs <em>Lhs</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lhs</em>' reference.
   * @see #getLhs()
   * @generated
   */
  void setLhs(Parameter value);

  /**
   * Returns the value of the '<em><b>Rhs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rhs</em>' attribute.
   * @see #setRhs(String)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getEqualsExpression_Rhs()
   * @model
   * @generated
   */
  String getRhs();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.EqualsExpression#getRhs <em>Rhs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rhs</em>' attribute.
   * @see #getRhs()
   * @generated
   */
  void setRhs(String value);

} // EqualsExpression
