/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.Expression#getAltCondition <em>Alt Condition</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.Expression#getMessages <em>Messages</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Alt Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt Condition</em>' containment reference.
   * @see #setAltCondition(LogicalExpression)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getExpression_AltCondition()
   * @model containment="true"
   * @generated
   */
  LogicalExpression getAltCondition();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.Expression#getAltCondition <em>Alt Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt Condition</em>' containment reference.
   * @see #getAltCondition()
   * @generated
   */
  void setAltCondition(LogicalExpression value);

  /**
   * Returns the value of the '<em><b>Messages</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.dipterv.text.minotorDsl.Message}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Messages</em>' containment reference list.
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getExpression_Messages()
   * @model containment="true"
   * @generated
   */
  EList<Message> getMessages();

} // Expression
