/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getLogicalExpression()
 * @model
 * @generated
 */
public interface LogicalExpression extends EObject
{
} // LogicalExpression
