/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Match Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.MatchMessage#getContext <em>Context</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.MatchMessage#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getMatchMessage()
 * @model
 * @generated
 */
public interface MatchMessage extends EObject
{
  /**
   * Returns the value of the '<em><b>Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' reference.
   * @see #setContext(ContextModel)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getMatchMessage_Context()
   * @model
   * @generated
   */
  ContextModel getContext();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.MatchMessage#getContext <em>Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' reference.
   * @see #getContext()
   * @generated
   */
  void setContext(ContextModel value);

  /**
   * Returns the value of the '<em><b>Content</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' reference.
   * @see #setContent(ContextFragment)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getMatchMessage_Content()
   * @model
   * @generated
   */
  ContextFragment getContent();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.MatchMessage#getContent <em>Content</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' reference.
   * @see #getContent()
   * @generated
   */
  void setContent(ContextFragment value);

} // MatchMessage
