/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isGreater <em>Greater</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isSmaller <em>Smaller</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isGreaterequals <em>Greaterequals</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isSmallerequals <em>Smallerequals</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isEquals <em>Equals</em>}</li>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isNotequals <em>Notequals</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getOperator()
 * @model
 * @generated
 */
public interface Operator extends EObject
{
  /**
   * Returns the value of the '<em><b>Greater</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Greater</em>' attribute.
   * @see #setGreater(boolean)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getOperator_Greater()
   * @model
   * @generated
   */
  boolean isGreater();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isGreater <em>Greater</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Greater</em>' attribute.
   * @see #isGreater()
   * @generated
   */
  void setGreater(boolean value);

  /**
   * Returns the value of the '<em><b>Smaller</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Smaller</em>' attribute.
   * @see #setSmaller(boolean)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getOperator_Smaller()
   * @model
   * @generated
   */
  boolean isSmaller();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isSmaller <em>Smaller</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Smaller</em>' attribute.
   * @see #isSmaller()
   * @generated
   */
  void setSmaller(boolean value);

  /**
   * Returns the value of the '<em><b>Greaterequals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Greaterequals</em>' attribute.
   * @see #setGreaterequals(boolean)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getOperator_Greaterequals()
   * @model
   * @generated
   */
  boolean isGreaterequals();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isGreaterequals <em>Greaterequals</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Greaterequals</em>' attribute.
   * @see #isGreaterequals()
   * @generated
   */
  void setGreaterequals(boolean value);

  /**
   * Returns the value of the '<em><b>Smallerequals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Smallerequals</em>' attribute.
   * @see #setSmallerequals(boolean)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getOperator_Smallerequals()
   * @model
   * @generated
   */
  boolean isSmallerequals();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isSmallerequals <em>Smallerequals</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Smallerequals</em>' attribute.
   * @see #isSmallerequals()
   * @generated
   */
  void setSmallerequals(boolean value);

  /**
   * Returns the value of the '<em><b>Equals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Equals</em>' attribute.
   * @see #setEquals(boolean)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getOperator_Equals()
   * @model
   * @generated
   */
  boolean isEquals();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isEquals <em>Equals</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Equals</em>' attribute.
   * @see #isEquals()
   * @generated
   */
  void setEquals(boolean value);

  /**
   * Returns the value of the '<em><b>Notequals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notequals</em>' attribute.
   * @see #setNotequals(boolean)
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getOperator_Notequals()
   * @model
   * @generated
   */
  boolean isNotequals();

  /**
   * Sets the value of the '{@link hu.bme.mit.dipterv.text.minotorDsl.Operator#isNotequals <em>Notequals</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Notequals</em>' attribute.
   * @see #isNotequals()
   * @generated
   */
  void setNotequals(boolean value);

} // Operator
