/**
 * generated by Xtext 2.24.0
 */
package hu.bme.mit.dipterv.text.minotorDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Params</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.dipterv.text.minotorDsl.Params#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getParams()
 * @model
 * @generated
 */
public interface Params extends EObject
{
  /**
   * Returns the value of the '<em><b>Params</b></em>' reference list.
   * The list contents are of type {@link hu.bme.mit.dipterv.text.minotorDsl.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' reference list.
   * @see hu.bme.mit.dipterv.text.minotorDsl.MinotorDslPackage#getParams_Params()
   * @model
   * @generated
   */
  EList<Parameter> getParams();

} // Params
